[package]
name = "hashi"
version = "0.1.0"
description = "Hashi program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "hashi"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
adapter = { path = "../adapter", features = ["cpi"] }