name: "CI"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - monorepo

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: 'Create env file'
        run: |
          echo "${{ secrets.CI_ENV_FILE }}" > ./packages/evm/.env

      - name: "Lint the code"
        run: "yarn lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn build"

      - name: "Test the contracts and generate the coverage report"
        run: "yarn coverage"

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: packages/evm/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
